# Generated by Django 5.0.6 on 2024-10-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_ratingandreviewtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingandreviewtable',
            old_name='loin_id',
            new_name='login_id',
        ),
    ]
