# Generated by Django 5.1.1 on 2024-09-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_rename_councellor_councellortable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintable',
            name='status',
        ),
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('Councellor', 'councellor')], default='pending', max_length=30, null=True),
        ),
    ]
