# Generated by Django 5.1.1 on 2024-10-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_remove_logintable_status_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('Councellor', 'councellor'), ('ADMIN', 'admin'), ('PENDING', 'pending')], default='PENDING', max_length=30, null=True),
        ),
    ]
