# Generated by Django 5.1.1 on 2024-10-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ADMIN', 'admin'), ('User', 'user'), ('Rejected', 'rejected'), ('Councellor', 'councellor')], default='PENDING', max_length=30, null=True),
        ),
    ]
