# Generated by Django 5.0.6 on 2024-10-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('User', 'user'), ('ADMIN', 'admin'), ('PENDING', 'pending'), ('Councellor', 'councellor'), ('Rejected', 'rejected')], default='PENDING', max_length=30, null=True),
        ),
    ]
