# Generated by Django 5.0.6 on 2024-10-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0008_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('Councellor', 'councellor'), ('Rejected', 'rejected'), ('User', 'user'), ('PENDING', 'pending')], default='PENDING', max_length=30, null=True),
        ),
    ]
