# Generated by Django 5.0.6 on 2024-10-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('Rejected', 'rejected'), ('PENDING', 'pending'), ('User', 'user'), ('Councellor', 'councellor')], default='pending', max_length=30, null=True),
        ),
    ]
