# Generated by Django 5.1.1 on 2024-10-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('User', 'user'), ('ADMIN', 'admin'), ('Rejected', 'rejected'), ('Councellor', 'councellor'), ('PENDING', 'pending')], default='pending', max_length=30, null=True),
        ),
    ]
