# Generated by Django 5.1.1 on 2024-10-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_alter_logintable_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='user_type',
            field=models.CharField(choices=[('Rejected', 'rejected'), ('PENDING', 'pending'), ('Councellor', 'councellor'), ('User', 'user'), ('ADMIN', 'admin')], default='pending', max_length=30, null=True),
        ),
    ]
